default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: test
  password: password
  host: localhost

development:
  primary:
    <<: *default
    database: development
  secondary:
    <<: *default
    database: development_secondary
    migrations_paths: db/migrate_secondary
